apiVersion: apps/v1
kind: Deployment
metadata:
  name: elering-adapter
  namespace: energy-company-dev
  labels:
    app: elering-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elering-adapter
  template:
    metadata:
      labels:
        app: elering-adapter
    spec:
      containers:
      - name: elering-adapter
        image: 480241654156.dkr.ecr.us-east-1.amazonaws.com/energy-company-elering-adapter-dev:latest
        ports:
        - containerPort: 5005
        envFrom:
        - configMapRef:
            name: elering-adapter-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 5005
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 5005
          initialDelaySeconds: 30
          periodSeconds: 10

