apiVersion: v1
kind: Service
metadata:
  name: elering-adapter
  namespace: energy-company-dev
  labels:
    app: elering-adapter
spec:
  selector:
    app: elering-adapter
  ports:
  - protocol: TCP
    port: 5005
    targetPort: 5005
  type: ClusterIP

