services:

  customer_db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: default
      POSTGRES_DB: customer-service-db
    ports:
      - "5433:5432"
    networks:
      - host

  elering-adapter:
    image: elering-adapter-api
    container_name: elering-adapter-service
    build:
      context: ./elering-adapter
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    environment:
      - ELERING_API_URL=https://estfeed.elering.ee/
    networks:
      - host

networks:
  host:
    driver: bridge

volumes:
  customer_db: