server:
  port: 4000

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                          allowedOrigins: ${ENERGY_COMPANY_CLIENT_URL:http://localhost:5173} # front-end client side url
                          allowedHeaders: "*"
                          allowedMethods:
                            - GET
                            - POST
                            - PUT
                            - DELETE
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          httpclient:
            connect-timeout: 60000
            response-timeout: 60s
          discovery:
            locator:
              enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}
    healthcheck:
      enabled: true

springdoc:
  show-actuator: true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
