apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  namespace: energy-company-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
      - name: customer-service
        image: 480241654156.dkr.ecr.us-east-1.amazonaws.com/energy-company-customer-service-dev:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_SERVICE_URL
          valueFrom:
            secretKeyRef:
              name: customer-db-secret
              key: url
        - name: DB_SERVICE_USERNAME
          valueFrom:
            secretKeyRef:
              name: customer-db-secret
              key: username
        - name: DB_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: customer-db-secret
              key: password
        - name: EUREKA_SERVICE_URL
          value: "http://eureka-server:8761/eureka/"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: energy-company-dev
spec:
  selector:
    app: customer-service
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
