apiVersion: batch/v1
kind: Job
metadata:
  name: consumption-service-db-migration
  namespace: energy-company-dev
spec:
  template:
    spec:
      containers:
      - name: consumption-service-db-migration
        image: 480241654156.dkr.ecr.us-east-1.amazonaws.com/energy-company-consumption-service-db-migration-dev:latest
        env:
        - name: DB_SERVICE_URL
          valueFrom:
            secretKeyRef:
              name: consumption-db-secret
              key: url
        - name: DB_SERVICE_USERNAME
          valueFrom:
            secretKeyRef:
              name: consumption-db-secret
              key: username
        - name: DB_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: consumption-db-secret
              key: password
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
      restartPolicy: OnFailure
  backoffLimit: 3
---
apiVersion: batch/v1
kind: Job
metadata:
  name: customer-service-db-migration
  namespace: energy-company-dev
spec:
  template:
    spec:
      containers:
      - name: customer-service-db-migration
        image: 480241654156.dkr.ecr.us-east-1.amazonaws.com/energy-company-customer-service-db-migration-dev:latest
        env:
        - name: DB_SERVICE_URL
          valueFrom:
            secretKeyRef:
              name: customer-db-secret
              key: url
        - name: DB_SERVICE_USERNAME
          valueFrom:
            secretKeyRef:
              name: customer-db-secret
              key: username
        - name: DB_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: customer-db-secret
              key: password
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
      restartPolicy: OnFailure
  backoffLimit: 3

