apiVersion: apps/v1
kind: Deployment
metadata:
  name: elering-adapter
  namespace: energy-company-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elering-adapter
  template:
    metadata:
      labels:
        app: elering-adapter
    spec:
      containers:
      - name: elering-adapter
        image: 480241654156.dkr.ecr.us-east-1.amazonaws.com/energy-company-elering-adapter-dev:latest
        ports:
        - containerPort: 5005
        env:
        - name: EUREKA_SERVICE_URL
          value: "http://eureka-server:8761/eureka/"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 5005
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 5005
          initialDelaySeconds: 30
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: elering-adapter
  namespace: energy-company-dev
spec:
  selector:
    app: elering-adapter
  ports:
  - protocol: TCP
    port: 5005
    targetPort: 5005
  type: ClusterIP
