apiVersion: batch/v1
kind: Job
metadata:
  name: customer-service-db-migration
  namespace: energy-company-dev
  labels:
    app: customer-service-db-migration
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: customer-service-db-migration
        image: 480241654156.dkr.ecr.us-east-1.amazonaws.com/energy-company-customer-service-db-migration-dev:latest
        env:
        - name: DB_SERVICE_URL
          valueFrom:
            secretKeyRef:
              name: customer-db-secret
              key: url
        - name: DB_SERVICE_USERNAME
          valueFrom:
            secretKeyRef:
              name: customer-db-secret
              key: username
        - name: DB_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: customer-db-secret
              key: password
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
  backoffLimit: 3

