apiVersion: v1
kind: Secret
metadata:
  name: customer-db-secret
  namespace: energy-company-dev
type: Opaque
data:
  # These will be populated by the deployment workflow from GitHub Secrets
  # The actual values are base64 encoded versions of the database credentials
  url: ""
  username: ""
  password: ""

