apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumption-service
  namespace: energy-company-dev
  labels:
    app: consumption-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumption-service
  template:
    metadata:
      labels:
        app: consumption-service
    spec:
      containers:
      - name: consumption-service
        image: 480241654156.dkr.ecr.us-east-1.amazonaws.com/energy-company-consumption-service-dev:latest
        ports:
        - containerPort: 5006
        envFrom:
        - configMapRef:
            name: consumption-service-config
        env:
        - name: DB_SERVICE_URL
          valueFrom:
            secretKeyRef:
              name: consumption-db-secret
              key: url
        - name: DB_SERVICE_USERNAME
          valueFrom:
            secretKeyRef:
              name: consumption-db-secret
              key: username
        - name: DB_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: consumption-db-secret
              key: password
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 5006
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 5006
          initialDelaySeconds: 30
          periodSeconds: 10

