apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: authentication-service
build:
  artifacts:
    - image: 480241654156.dkr.ecr.us-east-1.amazonaws.com/energy-company-authentication-service-dev
      jib: {}
  tagPolicy:
    gitCommit: {}
manifests:
  rawYaml:
    - ../k8s/privileges.yaml
    - k8s/**.yaml

